import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
            <title>Noah Reppert</title>
        </head>
      <body>

      <header>
          <nav className="flex bg-blue-400 text-white min-h-[3.5rem] items-center justify-center [gap:2rem]">
              <Link href="/">Home</Link>
              <Link href="/#projects">Projects</Link>
              <Link href="/#articles">Articles</Link>
              <Link href="/resume.pdf">Resume</Link>
          </nav>
      </header>

      {children}
      </body>
    </html>
  )
}
